config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions" }

  root 'static_pages#welcome'
  resources :users do 
    resources :friend_requests, except: [:edit]
    resources :posts do
      resources :likes, only: [:create, :destroy]
      resources :comments, except: [:index] do
        resources :likes, only: [:create, :destroy]
      end
    end
  end
  get '/feed' => 'static_pages#feed'
  get '/notifications' => 'static_pages#notifications'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def welcome
    
  end
  
  def feed
    # get posts from current user AND his friends
    feed_post_ids = [  ]
    friends(current_user).each { |f| feed_post_ids << f.id } 
    @feed_posts = Post.where("poster_id IN (?) OR poster_id = ?", feed_post_ids, current_user.id)
                      .order(created_at: :desc)
  end
  
  def notifications
    
  end
  
  private
  
    def friends(user)
      user.friends_from_active_requests |
      user.friends_from_passive_requests
    end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

end

app/views/static_pages/feed.html.erb
<h1>My Facebook Clone Feed</h1>

<%= link_to "My Profile", user_path(current_user) %>
<%= render 'layouts/post_form' %>

<%= render @feed_posts %>

app/views/static_pages/notifications.html.erb
<h1>My Notifications</h1>

<% current_user.notifications.unseen.order(created_at: :desc).each do |n| %>

	<% if n.source_type == "FriendRequest" && n.source.accepted == false %>
		<%= "#{n.sender.name.titleize} sent you a friend request." %>
		<%= link_to "Accept?", user_friend_request_url(current_user.id, n.sender_id), method: :patch %>
		
	<% elsif n.source_type == "Comment" && n.source.commenter_id != current_user.id %>
		<%= "#{n.sender.name.titleize} commented on your post." %>
		<%= link_to "View Comment", user_post_path(current_user.id, n.source.post_id), method: :get %>
		
	<% elsif n.source_type == "Like" && n.source.liker_id != current_user.id %>
		<%= "#{n.sender.name.titleize} liked your #{n.source.likeable_type.downcase}." %>
		
	<% end %>
	<% n.seen = true %>
	<% n.save %>
<% end %>

app/views/static_pages/welcome.html.erb
<h1>Welcome to Facebook Clone!</h1>

<%= link_to "Sign In", new_user_session_url %></br>
<%= link_to "Sign Up", new_user_registration_url %>