config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions" }

  root 'static_pages#welcome'
  resources :users do 
    resources :friend_requests, except: [:edit]
    resources :posts do
      resources :likes, only: [:create, :destroy]
      resources :comments, except: [:index] do
        resources :likes, only: [:create, :destroy]
      end
    end
  end
  get '/feed' => 'static_pages#feed'
  get '/notifications' => 'static_pages#notifications'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :commenter_id, :post_id,
    presence: true,
    numericality: true
  validates :text,
    presence: true
  
  has_many :notifications,
    as: :source
  belongs_to :commenter, 
    class_name: "User"
  belongs_to :post
  has_many :likes,
    as: :likeable,
    dependent: :destroy
  has_many :likers,
    through: :likes,
    class_name: "User",
    foreign_key: :id
    
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def new
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build
  end
  
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    redirect_to user_post_path(@post.poster_id, @post.id), notice: "Comment successfully posted!" if @comment.save
  end
  
  private
  
    def comment_params
      params.require(:comment).permit(:commenter_id, :post_id, :text)
    end
    
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<li id=<%= "p_#{comment.post.id}_c_#{comment.id}"%> >
	<%= comment.commenter.name %><%= " " %><%= comment.created_at %></br>
	<%= comment.text %>
	<% if comment.likers.include? current_user %>
		<%= link_to "Unlike", user_post_comment_like_path(comment.post.poster_id, 
														  comment.post.id, 
														  comment.id, 
														  current_users_like_of(comment).id), method: :delete %>
	<% else %>
		<%= link_to "Like", user_post_comment_likes_path(comment.post.poster_id, comment.post.id, comment.id), method: :create %>
	<% end %>
</li>

app/views/comments/_comment_form.html.erb
<%= form_tag(user_post_comments_path(params[:user_id], params[:post_id]), method: :post) do %>
	<%= hidden_field :comment, :commenter_id, value: current_user.id %>
	<%= hidden_field :comment, :post_id, value: params[:post_id] %>
	<%= text_area :comment, :text, size: "50x5" %></br>
	<%= submit_tag "Submit" %>
<% end %>

app/views/comments/new.html.erb
<h1>New Comment</h1>
<%= render 'comment_form' %>