config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions" }

  root 'static_pages#welcome'
  resources :users do 
    resources :friend_requests, except: [:edit]
    resources :posts do
      resources :likes, only: [:create, :destroy]
      resources :comments, except: [:index] do
        resources :likes, only: [:create, :destroy]
      end
    end
  end
  get '/feed' => 'static_pages#feed'
  get '/notifications' => 'static_pages#notifications'

end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :poster_id, 
    presence: true,
    numericality: true
  validates :text,
    presence: true
    
  belongs_to :poster, 
    class_name: "User"
  has_many :comments, 
    dependent: :destroy
  has_many :likes,
    as: :likeable,
    dependent: :destroy
  has_many :likers,
    through: :likes,
    class_name: "User",
    foreign_key: :id

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def show
    @post = Post.find_by(id: params[:id])
  end
  
  def new
    @post = Post.new
  end
  
  def create
    @post = current_user.posts.build(post_params)
    redirect_to feed_path, notice: "Post successfully created!" if @post.save
  end
  
  def update
    
  end
  
  def destroy
    
  end
  
  private
  
    def post_params
      params.require(:post).permit(:poster_id, :text)
    end
    
end

app/helpers/posts_helper.rb
module PostsHelper

end

app/views/posts/_post.html.erb
<%= post.poster.name %><%= " "%><%= post.created_at %></br>
<%= post.text %></br>
<%= pluralize(post.likes.count, "Like") unless post.likes.count == 0 %>
<%= pluralize(post.comments.count, "Comment") unless post.comments.count == 0 %>
<% if post.likers.include? current_user %>
	<%= link_to "Unlike", user_post_like_path(post.poster_id, post.id, current_users_like_of(post).id ), method: :delete %>
<% else %>
	<%= link_to "Like", user_post_likes_path(post.poster_id, post.id), method: :create %>
<% end %>
<%= link_to "Comment", new_user_post_comment_path(post.poster_id, post.id), method: :get %></br>
<ul>
<%= render post.comments %>
</ul>

app/views/posts/show.html.erb
<h1>Post <%= @post.id %></h1>
<%= render @post %>