config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions" }

  root 'static_pages#welcome'
  resources :users do 
    resources :friend_requests, except: [:edit]
    resources :posts do
      resources :likes, only: [:create, :destroy]
      resources :comments, except: [:index] do
        resources :likes, only: [:create, :destroy]
      end
    end
  end
  get '/feed' => 'static_pages#feed'
  get '/notifications' => 'static_pages#notifications'

end

app/views/layouts/_navbar.html.erb
<% if user_signed_in? %>
<header id="navbar" style="text-align: right;">
	<span id="navbar_notifs"><%= notification_count %></span>
	<% if current_user.notifications.unseen.count > 0 %>
		<span id="navbar_view"><%= link_to "View", notifications_path %></span>
	<% end %>
	<span id="navbar_home"><%= link_to "Home", feed_path %></span>
	<span id="navbar_sign_out"><%= link_to "Sign Out", destroy_user_session_url, method: :delete %></span>
</header>
<% end %>

app/views/layouts/_post_form.html.erb
<h2>Write a New Post</h2>
<%= form_tag(user_posts_path(current_user), method: :post) do %>
	<%= hidden_field :post, :poster_id, value: current_user.id %>
	<div id="post_form">
		<%= text_area :post, :text, size: "50x5" %>
	</div></br>
	<%= submit_tag "Post Now" %> 
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FacebookClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/navbar' %>
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
		
<%= yield %>

</body>
</html>